spin_manifest_version = 2

[application]
name = "api"
version = "0.1.0"
authors = ["Noé Tarbouriech <noe.tarbouriech@etu.umontpellier.fr>"]
description = ""

[variables]
db_url = { required = true }

[[trigger.http]]
route = "/..."
component = "api"

[component.api]
source = "main.wasm"
allowed_outbound_hosts = ["*://{{ db_url }}:5432"]
[component.api.variables]
db_url = "{{ db_url }}"
db_username = "test"
db_password = "test"
db_name = "test"
[component.api.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
